name: Check for release

on:
  push:
    branches:
      - 'main'

jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release
        uses: actions/github-script@v7
        with:
          script: |
            const pull_number = context.payload.head_commit.message?.match(/Merge pull request #(\d+) from/)
            if (!pull_number) {
              console.log('No pull number. Skip')
              process.exit(0)
            }

            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yaml',
              ref: 'main',
              inputs: {
                context: JSON.stringify(context)
              },
            })