name: Verify PR

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  verify:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Installn node packages
        run: npm install plist mime-types
      - name: Verify
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/pr.js')
            await script({github, context})